### ISSUE TITLE
Missing <head> tag

### ISSUE THREAD

**Issue by jema28** [fack2/PORTFOLIO#10]
A few things to add here:
1. An opening and closing `<head>` tag around the title, meta and link tags
1. Add `<meta name="viewport" content="width=device-width, initial-scale=1.0">` to make sure your page renders correctly on mobile screens. 
https://github.com/fack2/PORTFOLIO/blob/49662fff19761624a101133412ec240e94ea7a52/index.html#L3-L10

**Comment by wajdomahdi** [comment]
using meta made some changes in our design so we promise you to use it next time , and we use percentage instead of them
