### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by shahenazmonia** [fack2/PORTFOLIO#28]
you got a good accessibility rate, liked it 😍  and try to fix the rest of the accessibility issues!

![](https://files.gitter.im/shahenazmonia/B3Y4/Screenshot-2019-06-20-at-9.30.59-AM.png)

**Comment by wajdomahdi** [comment]
we fixed it and it becomes 100% @shahenazmonia

**Comment by shahenazmonia** [comment]
@wajdomahdi cool, good job guys 👏
